routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// for admins
Route::group(['middleware' => ['auth', 'role:admin']], function() {

    Route::get('/users/export', 'App\Http\Controllers\UsersExportController@export');
    Route::resource('users', 'App\Http\Controllers\UsersController');
    Route::post('/users/{user}', 'App\Http\Controllers\UsersController@update');

    Route::resource('people', 'App\Http\Controllers\PeopleController');
    Route::post('/people/{person}', 'App\Http\Controllers\PeopleController@update');

    Route::resource('mails', 'App\Http\Controllers\EmailsController');
    Route::post('/mails/{email}', 'App\Http\Controllers\EmailsController@update');

    Route::resource('phones', 'App\Http\Controllers\PhonesController');
    Route::post('/phones/{phone}', 'App\Http\Controllers\PhonesController@update');

    Route::resource('institutes', 'App\Http\Controllers\InstitutesController');
    Route::post('institutes/{institute}', 'App\Http\Controllers\InstitutesController@update');

    Route::get('institutes/{institute}/edit/category', 'App\Http\Controllers\InstitutesController@editCategory')->name('institutes.edit.category');
    Route::post('institutes/{institute}/update/category', 'App\Http\Controllers\InstitutesController@updateCategory')->name('institutes.update.category');

    Route::get('institutes/{institute}/edit/specialities', 'App\Http\Controllers\InstitutesController@editSpecialities')->name('institutes.edit.specialities');
    Route::post('institutes/{institute}/update/specialities', 'App\Http\Controllers\InstitutesController@updateSpecialities')->name('institutes.update.specialities');

    Route::post('institutes/for/person/{person}', 'App\Http\Controllers\InstitutesController@categoryselectedPerson')->name('institutes.for.person'); //person
    Route::post('institutes/for/person/selected/{person}', 'App\Http\Controllers\InstitutesController@selectedInstitutePerson')->name('institutes.for.person.selected'); //person
    Route::get('institutes/edit/address/{institute}', 'App\Http\Controllers\InstitutesController@editAddress')->name('institutes.edit.address');
    Route::post('institutes/{institute}/update/address', 'App\Http\Controllers\InstitutesController@updateAddress')->name('institutes.update.address');

    Route::post('institutes/category/selected', 'App\Http\Services\InstitutesService@instituteCategorySelected')->name('institutes.category.selected'); //new institute
    Route::post('institutes/select/parent', 'App\Http\Services\InstitutesService@selectParentInstitute')->name('institutes.select.parent'); //new institute
    Route::get('institutes/select/parent/back', 'App\Http\Services\InstitutesService@backSelectedParentInstitute')->name('institutes.select.parent.back'); //new institute
    Route::post('institutes/save/address', 'App\Http\Controllers\InstitutesController@saveAddress')->name('institutes.save.address'); //new institute
    Route::post('institutes/save/specialities', 'App\Http\Controllers\InstitutesController@saveSpecialities')->name('institutes.save.specialities'); //new institute

    Route::resource('categories', 'App\Http\Controllers\CategoriesController');
    Route::get('categories/index/people/{person}', 'App\Http\Controllers\CategoriesController@indexPeople')->name('categories.index.people'); //person
    Route::get('categories/edit/people/{person}', 'App\Http\Controllers\CategoriesController@editPeople')->name('categories.edit.people'); //person

    Route::resource('countries', 'App\Http\Controllers\CountriesController');
    Route::resource('cities', 'App\Http\Controllers\CitiesController');
    Route::resource('addresses', 'App\Http\Controllers\AddressesController');
    Route::resource('specialities', 'App\Http\Controllers\SpecialitiesController');

    Route::resource('events', 'App\Http\Controllers\EventsController');
    Route::post('events/{event}', 'App\Http\Controllers\EventsController@update');
    Route::get('events/send/invitation/{$id}', 'App\Http\Controllers\EventsController@sendEventMail')->name('events.send.invitation');
    Route::post('events/email/sent', 'App\Http\Controllers\EventsController@eventMailSent')->name('events.email.sent');

    Route::resource('participants', 'App\Http\Controllers\ParticipantsController');
    Route::post('participants/update/roles', 'App\Http\Controllers\ParticipantsController@updateRoles')->name('participant.update.roles');
    Route::get('participants/selectnew/options', 'App\Http\Services\EventsService@addParticipantsOption')->name('participants.selectnew.options');
    Route::post('participants/select/event/email', 'App\Http\Services\EventsService@selectEventEmail')->name('participants.select.event.email');
    Route::post('participants/eventemail/selected', 'App\Http\Services\EventsService@eventEmailSelected')->name('participants.eventemail.selected');

    Route::resource('eventemails', 'App\Http\Controllers\EventemailsController');
    Route::post('eventemails/{eventemail}', 'App\Http\Controllers\EventemailsController@update');

    Route::resource('presentations', 'App\Http\Controllers\PresentationsController');
    Route::post('presentations/{presentation}', 'App\Http\Controllers\PresentationsController@update');
});

//auth route for both
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
    Route::get('/dashboard/profile/myprofile', 'App\Http\Controllers\DashboardController@myprofile')->name('dashboard.myprofile');

    Route::get('/profile/{user}/edit', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::post('/profile/{user}', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
    Route::get('/profile/{user}/edit-password', 'App\Http\Controllers\ProfileController@editPassword')->name('profile.edit-password');
    Route::post('/profile/{user}/update-password', 'App\Http\Controllers\ProfileController@updatePassword')->name('profile.update-password');

    Route::get('/partners/export', 'App\Http\Controllers\PartnersExportController@export');
    Route::resource('people', 'App\Http\Controllers\PeopleController')->only('index', 'show');
    Route::get('/people/sort/desc', 'App\Http\Controllers\PeopleController@indexDesc')->name('people.sort.desc');
    Route::get('/people/sort/institute', 'App\Http\Controllers\PeopleController@sortByInstitute')->name('people.sort.institute');
    Route::get('/people/sort/institute/desc', 'App\Http\Controllers\PeopleController@sortByInstituteDesc')->name('people.sort.institute.desc');
    Route::get('/people/sort/name', 'App\Http\Controllers\PeopleController@sortByLastname')->name('people.sort.name');
    Route::get('/people/sort/name/desc', 'App\Http\Controllers\PeopleController@sortByLastnameDesc')->name('people.sort.name.desc');
    Route::get('/people/sort/position', 'App\Http\Controllers\PeopleController@sortByPosition')->name('people.sort.position');
    Route::get('/people/sort/position/desc', 'App\Http\Controllers\PeopleController@sortByPositionDesc')->name('people.sort.position.desc');

    Route::resource('institutes', 'App\Http\Controllers\InstitutesController')->only('index', 'show');

    Route::resource('events', 'App\Http\Controllers\EventsController')->only('index', 'show');
    Route::get('/events/all/export', 'App\Http\Controllers\EventsExportController@export');

    Route::resource('eventemails', 'App\Http\Controllers\EventemailsController')->only('show');
    Route::resource('presentations', 'App\Http\Controllers\PresentationsController')->only('show');
});

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'category_name',
    ];

    public function institutes()
    {
        return $this->hasMany(Institute::class);
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Institute;
use App\Models\Person;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->session()->get('category_id') != null) {
            $category_id = $request->session()->get('category_id');
        } else {
            $category_id = 0;
        }
        $categoriesAll = Category::all();
        $categories = $categoriesAll->whereNotIn('id', [4, 6]);

        return view('categories.institute-category', compact( 'categories', 'category_id'));
    }

    public function indexPeople(Request $request)
    {
        $url = $request->getRequestUri();
        $request->session()->put('url', $url);

        $categories = Category::all();

        if($request->session()->get('category_id') != null) {
            $category_id = $request->session()->get('category_id');
        } else {
            $category_id = 0;
        }

        $person_id = $request->session()->get('person_id');
        return view('categories.select', compact('categories', 'category_id', 'person_id'));
    }

    public function editPeople(Request $request, $id)
    {
        $url = $request->getRequestUri();
        $request->session()->flash('url', $url);

        $categories = Category::all();
        $person = Person::findOrFail($id);

        if($person->institute_id != null) {
            $institute = Institute::findOrFail($person->institute_id);
            $category_id = $institute->category_id;

        } else {
            $category_id = 0;
        }

        $request->session()->flash('category_id', $category_id);

        return view('categories.edit-for-person', compact('categories', 'category_id', 'person'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $uri = $request->getRequestUri();

        $request->validate([
            'category_name' => ['required', 'string', 'max:100'],
        ]);

        $category = Category::create([
            'category_name' => $request->category_name,
        ]);

        $category->save();

        return redirect($uri);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új intézmény kategória') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header">

                            </div>

                            <div class="card-body">

                                <form method="POST" action="{{ route('categories.store') }}" enctype="multipart/form-data">
                                    @csrf

                                    <div class="form-group row">
                                        <label for="category_name" class="col-md-4 col-form-label text-md-right">{{ __('Kategória neve:') }}</label>

                                        <div class="col-md-6">
                                            <input type="text" class="form-control rounded @error('category_name') is-invalid @enderror" name="category_name" value="{{ old('category_name') }}"autocomplete="category_name">

                                            @error('category_name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="card-footer">
                                        <div class="form-group row mb-0 justify-content-center">

                                            <div class="col-md-4 offset-md-0">
                                                <a href="{{ route('categories.index') }}"><button type="button" class="btn btn-secondary">@include('components.icons.left-icon'){{ __('Vissza') }}</button></a>
                                            </div>

                                            <div class="col-md-0 offset-md-4">
                                                <button type="submit" class="btn btn-primary">{{ __('Mentés') }}</button>
                                            </div>

                                        </div>
                                    </div>

                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/categories/edit-for-institute.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Intézmény szerkesztése') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header text-center">
                                <h3 class="text-center">{{ $institute->institute_name }}</h3>
                            </div>

                            <form method="POST" action="{{ route('institutes.update.category', $institute->id) }}" enctype="multipart/form-data">
                                @csrf
                            <div class="card-body">
                                @include('components.forms.select-category-form')
                            </div>
                                @include('components.forms.edit-footer')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/categories/edit-for-person.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Partner szerkesztése') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header text-center">
                                <h3 class="text-center">{{ $person->title }} {{ $person->lastname }} {{ $person->firstname }}</h3>
                            </div>

                            <form method="POST" action="{{ route('institutes.for.person', $person->id) }}" enctype="multipart/form-data">
                                @csrf
                                <div class="card-body">
                                    @include('components.forms.select-category-form')
                                </div>
                                    @include('components.forms.partner-steps-footer', ['url' => 'people/'. $person->id])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/categories/institute-category.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új intézmény') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header">

                                <!-- Circles which indicates the steps of the form: -->
                                <div class="step-div">
                                    <span class="step step-finish"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <button type="button" class="close" aria-label="Close">
                                        <a class="text-secondary text-decoration-none" href="{{ route('institutes.index') }}"><span>&times;</span></a>
                                    </button>
                                </div>

                            </div>

                            <form method="POST" action="{{ route('institutes.category.selected') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                @include('components.forms.select-category-form')
                            </div>
                                @include('components.forms.partner-steps-footer', ['url' => 'institutes'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/categories/select.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új partner') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header">

                                <!-- Circles which indicates the steps of the form: -->
                                <div class="step-div">
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step"></span>
                                    <button type="button" class="close" aria-label="Close">
                                        <a class="text-secondary text-decoration-none" href="{{ route('people.index') }}"><span>&times;</span></a>
                                    </button>
                                </div>
                            </div>

                            <form method="POST" action="{{ route('institutes.for.person', $person_id) }}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                @include('components.forms.select-category-form')
                            </div>
                                @include('components.forms.partner-steps-footer', ['url' => 'phones/create'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection