routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// for admins
Route::group(['middleware' => ['auth', 'role:admin']], function() {

    Route::get('/users/export', 'App\Http\Controllers\UsersExportController@export');
    Route::resource('users', 'App\Http\Controllers\UsersController');
    Route::post('/users/{user}', 'App\Http\Controllers\UsersController@update');

    Route::resource('people', 'App\Http\Controllers\PeopleController');
    Route::post('/people/{person}', 'App\Http\Controllers\PeopleController@update');

    Route::resource('mails', 'App\Http\Controllers\EmailsController');
    Route::post('/mails/{email}', 'App\Http\Controllers\EmailsController@update');

    Route::resource('phones', 'App\Http\Controllers\PhonesController');
    Route::post('/phones/{phone}', 'App\Http\Controllers\PhonesController@update');

    Route::resource('institutes', 'App\Http\Controllers\InstitutesController');
    Route::post('institutes/{institute}', 'App\Http\Controllers\InstitutesController@update');

    Route::get('institutes/{institute}/edit/category', 'App\Http\Controllers\InstitutesController@editCategory')->name('institutes.edit.category');
    Route::post('institutes/{institute}/update/category', 'App\Http\Controllers\InstitutesController@updateCategory')->name('institutes.update.category');

    Route::get('institutes/{institute}/edit/specialities', 'App\Http\Controllers\InstitutesController@editSpecialities')->name('institutes.edit.specialities');
    Route::post('institutes/{institute}/update/specialities', 'App\Http\Controllers\InstitutesController@updateSpecialities')->name('institutes.update.specialities');

    Route::post('institutes/for/person/{person}', 'App\Http\Controllers\InstitutesController@categoryselectedPerson')->name('institutes.for.person'); //person
    Route::post('institutes/for/person/selected/{person}', 'App\Http\Controllers\InstitutesController@selectedInstitutePerson')->name('institutes.for.person.selected'); //person
    Route::get('institutes/edit/address/{institute}', 'App\Http\Controllers\InstitutesController@editAddress')->name('institutes.edit.address');
    Route::post('institutes/{institute}/update/address', 'App\Http\Controllers\InstitutesController@updateAddress')->name('institutes.update.address');

    Route::post('institutes/category/selected', 'App\Http\Services\InstitutesService@instituteCategorySelected')->name('institutes.category.selected'); //new institute
    Route::post('institutes/select/parent', 'App\Http\Services\InstitutesService@selectParentInstitute')->name('institutes.select.parent'); //new institute
    Route::get('institutes/select/parent/back', 'App\Http\Services\InstitutesService@backSelectedParentInstitute')->name('institutes.select.parent.back'); //new institute
    Route::post('institutes/save/address', 'App\Http\Controllers\InstitutesController@saveAddress')->name('institutes.save.address'); //new institute
    Route::post('institutes/save/specialities', 'App\Http\Controllers\InstitutesController@saveSpecialities')->name('institutes.save.specialities'); //new institute

    Route::resource('categories', 'App\Http\Controllers\CategoriesController');
    Route::get('categories/index/people/{person}', 'App\Http\Controllers\CategoriesController@indexPeople')->name('categories.index.people'); //person
    Route::get('categories/edit/people/{person}', 'App\Http\Controllers\CategoriesController@editPeople')->name('categories.edit.people'); //person

    Route::resource('countries', 'App\Http\Controllers\CountriesController');
    Route::resource('cities', 'App\Http\Controllers\CitiesController');
    Route::resource('addresses', 'App\Http\Controllers\AddressesController');
    Route::resource('specialities', 'App\Http\Controllers\SpecialitiesController');

    Route::resource('events', 'App\Http\Controllers\EventsController');
    Route::post('events/{event}', 'App\Http\Controllers\EventsController@update');
    Route::get('events/send/invitation/{$id}', 'App\Http\Controllers\EventsController@sendEventMail')->name('events.send.invitation');
    Route::post('events/email/sent', 'App\Http\Controllers\EventsController@eventMailSent')->name('events.email.sent');

    Route::resource('participants', 'App\Http\Controllers\ParticipantsController');
    Route::post('participants/update/roles', 'App\Http\Controllers\ParticipantsController@updateRoles')->name('participant.update.roles');
    Route::get('participants/selectnew/options', 'App\Http\Services\EventsService@addParticipantsOption')->name('participants.selectnew.options');
    Route::post('participants/select/event/email', 'App\Http\Services\EventsService@selectEventEmail')->name('participants.select.event.email');
    Route::post('participants/eventemail/selected', 'App\Http\Services\EventsService@eventEmailSelected')->name('participants.eventemail.selected');

    Route::resource('eventemails', 'App\Http\Controllers\EventemailsController');
    Route::post('eventemails/{eventemail}', 'App\Http\Controllers\EventemailsController@update');

    Route::resource('presentations', 'App\Http\Controllers\PresentationsController');
    Route::post('presentations/{presentation}', 'App\Http\Controllers\PresentationsController@update');
});

//auth route for both
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
    Route::get('/dashboard/profile/myprofile', 'App\Http\Controllers\DashboardController@myprofile')->name('dashboard.myprofile');

    Route::get('/profile/{user}/edit', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::post('/profile/{user}', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
    Route::get('/profile/{user}/edit-password', 'App\Http\Controllers\ProfileController@editPassword')->name('profile.edit-password');
    Route::post('/profile/{user}/update-password', 'App\Http\Controllers\ProfileController@updatePassword')->name('profile.update-password');

    Route::get('/partners/export', 'App\Http\Controllers\PartnersExportController@export');
    Route::resource('people', 'App\Http\Controllers\PeopleController')->only('index', 'show');
    Route::get('/people/sort/desc', 'App\Http\Controllers\PeopleController@indexDesc')->name('people.sort.desc');
    Route::get('/people/sort/institute', 'App\Http\Controllers\PeopleController@sortByInstitute')->name('people.sort.institute');
    Route::get('/people/sort/institute/desc', 'App\Http\Controllers\PeopleController@sortByInstituteDesc')->name('people.sort.institute.desc');
    Route::get('/people/sort/name', 'App\Http\Controllers\PeopleController@sortByLastname')->name('people.sort.name');
    Route::get('/people/sort/name/desc', 'App\Http\Controllers\PeopleController@sortByLastnameDesc')->name('people.sort.name.desc');
    Route::get('/people/sort/position', 'App\Http\Controllers\PeopleController@sortByPosition')->name('people.sort.position');
    Route::get('/people/sort/position/desc', 'App\Http\Controllers\PeopleController@sortByPositionDesc')->name('people.sort.position.desc');

    Route::resource('institutes', 'App\Http\Controllers\InstitutesController')->only('index', 'show');

    Route::resource('events', 'App\Http\Controllers\EventsController')->only('index', 'show');
    Route::get('/events/all/export', 'App\Http\Controllers\EventsExportController@export');

    Route::resource('eventemails', 'App\Http\Controllers\EventemailsController')->only('show');
    Route::resource('presentations', 'App\Http\Controllers\PresentationsController')->only('show');
});

require __DIR__.'/auth.php';

app/Models/Institute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Institute extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'institute_name',
        'short_name',
        'category_id',
        'address_id',
        'parent_id'
    ];

    public function childinstitutes(){
        return $this->hasMany('App\Models\Institute', 'parent_id');
    }

    public function parentinstitute(){
        return $this->belongsTo('App\Models\Institute', 'parent_id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function people()
    {
        return $this->hasMany(Person::class);
    }

    public function address()
    {
        return $this->belongsTo(Address::class);
    }

    public function specialities()
    {
        return $this->belongsToMany(Speciality::class);
    }
}

resources/views/institutes/childinstituteList.blade.php
@foreach($childinstitutes as $childinstitute)
    <table class="table">
        <tr>
            <td class="col-md-10">
                <ul style="list-style-type:none;">
                    @if(count($childinstitute->childinstitutes))
                        <li>{{$childinstitute->institute_name}}  <button class="btn btn-sm btn-outline-secondary" type="button" data-toggle="collapse" data-target="#collapse{{$childinstitute->id}}" aria-expanded="false" aria-controls="collapse{{$childinstitute->id}}"> @include('components.icons.down-icon')</button></li>
                        <div class="collapse" id="collapse{{$childinstitute->id}}">
                            @include('institutes.childinstituteList',['childinstitutes' => $childinstitute->childinstitutes])
                        </div>
                    @else
                        <li>{{$childinstitute->institute_name}}</li>
                    @endif
                    @foreach($institutes_specialities as $allinstitute)
                        @if($allinstitute->id == $childinstitute->id)
                            @foreach($allinstitute->specialities as $speciality)
                                <span class="badge badge-pill {{ $speciality->colour_class }}">
                                    {{ $speciality->speciality_name }}
                                </span>
                            @endforeach
                        @endif
                    @endforeach
                </ul>
            </td>
            <td class="col-md-1">
                <button class="btn btn-success btn-show">
                    <a class="text-light" href="{{ route('institutes.show', $childinstitute->id )}}">@include('components.icons.eye-icon')</a>
                </button>
            </td>
            @if($childinstitute->childinstitutes()->count() === 0 && $childinstitute->people()->count() === 0)
                @if(Auth::user()->hasRole('admin'))
                <td class="col-md-1">
                    <!-- Button trigger modal -->
                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ $id = $childinstitute->id }}">
                        @include('components.icons.delete-icon')
                    </button>

                    <!-- Modal -->
                    @include('components.delede-modal', ['route' => 'institutes.destroy', 'headertext' => 'Intézmény törlése',
                            'bodytext' => 'Biztosan törölni akarja az intézményt minden adatával?' ])

                </td>
                @endif
            @endif
        </tr>
    </table>
@endforeach

resources/views/institutes/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új intézmény') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header">

                                <!-- Circles which indicates the steps of the form: -->
                                <div class="step-div">
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <button type="button" class="close" aria-label="Close">
                                        <a class="text-secondary text-decoration-none" href="{{ route('institutes.index') }}"><span>&times;</span></a>
                                    </button>
                                </div>
                            </div>

                            <form method="POST" action="{{ route('institutes.store') }}" enctype="multipart/form-data">
                                @csrf
                            <div class="card-body">
                                @include('components.forms.institute-form')
                            </div>
                                @include('components.forms.partner-steps-footer', ['url' => 'institutes/select/parent/back'])

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/institutes/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Intézmény szerkesztése') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header">
                                <h5 class="text-center">{{ $institute->institute_name }}</h5>
                            </div>

                            <form method="POST" action="{{ route('institutes.update', $institute->id) }}" enctype="multipart/form-data">
                                @csrf
                            <div class="card-body">
                                @include('components.forms.institute-form')
                            </div>
                                @include('components.forms.edit-footer')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/institutes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')
        <div class="content pl-1 pr-1">
            <div Class=" welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Intézmények') }}</h1></div>
            <div class="container user-table">
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <table class="table">
                            @foreach($institutes as $institute)
                                <tr>
                                    <th class="col-md-10">
                                        <ul class="list-unstyled">
                                            @if(count($institute->childinstitutes))
                                                <li>{{$institute->institute_name}}
                                                    <button class="btn btn-sm btn-outline-secondary" type="button" data-toggle="collapse" data-target="#collapse{{$institute->id}}" aria-expanded="false" aria-controls="collapse{{$institute->id}}">
                                                        @include('components.icons.down-icon')
                                                    </button>

                                                </li>
                                                <div class="collapse" id="collapse{{$institute->id}}">
                                                    @include('institutes.childinstituteList',['childinstitutes' => $institute->childinstitutes])
                                                </div>
                                            @else
                                                <li>{{$institute->institute_name}}</li>
                                            @endif
                                                @foreach($institutes_specialities as $allinstitute)
                                                    @if($allinstitute->id == $institute->id)
                                                        @foreach($allinstitute->specialities as $speciality)
                                                            <span class="badge badge-pill {{ $speciality->colour_class }}">
                                                                {{ $speciality->speciality_name }}
                                                            </span>
                                                        @endforeach
                                                    @endif
                                                @endforeach
                                        </ul>
                                    </th>
                                    <td>
                                        <button class="btn btn-success btn-show">
                                            <a class="text-light" href="{{ route('institutes.show', $institute->id )}}">@include('components.icons.eye-icon')</a>
                                        </button>
                                    </td>
                                    @if($institute->childinstitutes()->count() === 0 && $institute->people()->count() === 0)
                                        @if(Auth::user()->hasRole('admin'))
                                        <td>
                                        <!-- Button trigger modal -->
                                            <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ $id = $institute->id }}">
                                                @include('components.icons.delete-icon')
                                            </button>

                                            <!-- Modal -->
                                            @include('components.delede-modal', ['route' => 'institutes.destroy', 'headertext' => 'Intézmény törlése',
                                                    'bodytext' => 'Biztosan törölni akarja az intézményt minden adatával?' ])

                                        </td>
                                        @endif
                                    @endif
                                </tr>
                            @endforeach

                        </table>

                        <div class="row">
                            <div class="col-12 ">
                                {{$institutes->links()}}
                            </div>
                        </div>

                        @if(session('status'))
                            <div class="alert alert-danger">
                                {{ session('status') }}
                            </div>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/institutes/parent-selection.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új intézmény') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-10">

                        <div class="card">
                            <div class="card-header">

                                <!-- Circles which indicates the steps of the form: -->
                                <div class="step-div">
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <button type="button" class="close" aria-label="Close">
                                        <a class="text-secondary text-decoration-none" href="{{ route('institutes.index') }}"><span>&times;</span></a>
                                    </button>
                                </div>
                            </div>

                            <form method="POST" action="{{ route('institutes.select.parent') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">

                            <!--Select Option parent institute -->
                                <div class="form-group row">
                                    <label for="parent_id" class="col-md-3 col-form-label text-md-right">{{ __('Felettes intézmény:') }}</label>
                                    <div class="col-md-6">
                                        <select name="parent_id"  class="form-control">
                                            <option value="0">{{ __('Nincs') }}</option>
                                            @foreach($institutes as $institute)
                                                <option value="{{ $institute->id }}" {{ old('parent_id', $parent_id) ==  $institute->id  ? 'selected' : '' }}>{{ $institute->path }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                            </div>
                                @include('components.forms.partner-steps-footer', ['url' => 'categories'])

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/institutes/select-edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Partner szerkesztése') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header text-center">
                                <h3 class="text-center">{{ $person->title }} {{ $person->lastname }} {{ $person->firstname }}</h3>
                            </div>
                            <form method="POST" action="{{ route('institutes.for.person.selected', $person_id) }}" enctype="multipart/form-data">
                                @csrf
                            <div class="card-body">
                                @include('components.forms.select-institute')
                            </div>
                                @include('components.forms.edit-footer')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/institutes/select.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új partner') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-10">

                        <div class="card">
                            <div class="card-header">

                                <!-- Circles which indicates the steps of the form: -->
                                <div class="step-div">
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <span class="step step-finish"></span>
                                    <button type="button" class="close" aria-label="Close">
                                        <a class="text-secondary text-decoration-none" href="{{ route('people.index') }}"><span>&times;</span></a>
                                    </button>
                                </div>
                            </div>

                            <form method="POST" action="{{ route('institutes.for.person.selected', $person_id) }}" enctype="multipart/form-data">
                                @csrf
                            <div class="card-body">

                                @include('components.forms.select-institute')

                            </div>
                            <div class="card-footer">
                                <div class="form-group row mb-0 justify-content-center">

                                    <div class="col-md-4 offset-md-0">
                                        <button type="button" class="btn btn-secondary">
                                            <a class="text-decoration-none text-light" href="{{ url('categories/index/people/'.$person_id)}}">@include('components.icons.left-icon'){{ __('Vissza') }}</a>
                                        </button>
                                    </div>

                                    <div class="col-md-0 offset-md-4">
                                        <button type="submit" class="btn btn-primary">{{ __('Mentés') }}</button>
                                    </div>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection