routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// for admins
Route::group(['middleware' => ['auth', 'role:admin']], function() {

    Route::get('/users/export', 'App\Http\Controllers\UsersExportController@export');
    Route::resource('users', 'App\Http\Controllers\UsersController');
    Route::post('/users/{user}', 'App\Http\Controllers\UsersController@update');

    Route::resource('people', 'App\Http\Controllers\PeopleController');
    Route::post('/people/{person}', 'App\Http\Controllers\PeopleController@update');

    Route::resource('mails', 'App\Http\Controllers\EmailsController');
    Route::post('/mails/{email}', 'App\Http\Controllers\EmailsController@update');

    Route::resource('phones', 'App\Http\Controllers\PhonesController');
    Route::post('/phones/{phone}', 'App\Http\Controllers\PhonesController@update');

    Route::resource('institutes', 'App\Http\Controllers\InstitutesController');
    Route::post('institutes/{institute}', 'App\Http\Controllers\InstitutesController@update');

    Route::get('institutes/{institute}/edit/category', 'App\Http\Controllers\InstitutesController@editCategory')->name('institutes.edit.category');
    Route::post('institutes/{institute}/update/category', 'App\Http\Controllers\InstitutesController@updateCategory')->name('institutes.update.category');

    Route::get('institutes/{institute}/edit/specialities', 'App\Http\Controllers\InstitutesController@editSpecialities')->name('institutes.edit.specialities');
    Route::post('institutes/{institute}/update/specialities', 'App\Http\Controllers\InstitutesController@updateSpecialities')->name('institutes.update.specialities');

    Route::post('institutes/for/person/{person}', 'App\Http\Controllers\InstitutesController@categoryselectedPerson')->name('institutes.for.person'); //person
    Route::post('institutes/for/person/selected/{person}', 'App\Http\Controllers\InstitutesController@selectedInstitutePerson')->name('institutes.for.person.selected'); //person
    Route::get('institutes/edit/address/{institute}', 'App\Http\Controllers\InstitutesController@editAddress')->name('institutes.edit.address');
    Route::post('institutes/{institute}/update/address', 'App\Http\Controllers\InstitutesController@updateAddress')->name('institutes.update.address');

    Route::post('institutes/category/selected', 'App\Http\Services\InstitutesService@instituteCategorySelected')->name('institutes.category.selected'); //new institute
    Route::post('institutes/select/parent', 'App\Http\Services\InstitutesService@selectParentInstitute')->name('institutes.select.parent'); //new institute
    Route::get('institutes/select/parent/back', 'App\Http\Services\InstitutesService@backSelectedParentInstitute')->name('institutes.select.parent.back'); //new institute
    Route::post('institutes/save/address', 'App\Http\Controllers\InstitutesController@saveAddress')->name('institutes.save.address'); //new institute
    Route::post('institutes/save/specialities', 'App\Http\Controllers\InstitutesController@saveSpecialities')->name('institutes.save.specialities'); //new institute

    Route::resource('categories', 'App\Http\Controllers\CategoriesController');
    Route::get('categories/index/people/{person}', 'App\Http\Controllers\CategoriesController@indexPeople')->name('categories.index.people'); //person
    Route::get('categories/edit/people/{person}', 'App\Http\Controllers\CategoriesController@editPeople')->name('categories.edit.people'); //person

    Route::resource('countries', 'App\Http\Controllers\CountriesController');
    Route::resource('cities', 'App\Http\Controllers\CitiesController');
    Route::resource('addresses', 'App\Http\Controllers\AddressesController');
    Route::resource('specialities', 'App\Http\Controllers\SpecialitiesController');

    Route::resource('events', 'App\Http\Controllers\EventsController');
    Route::post('events/{event}', 'App\Http\Controllers\EventsController@update');
    Route::get('events/send/invitation/{$id}', 'App\Http\Controllers\EventsController@sendEventMail')->name('events.send.invitation');
    Route::post('events/email/sent', 'App\Http\Controllers\EventsController@eventMailSent')->name('events.email.sent');

    Route::resource('participants', 'App\Http\Controllers\ParticipantsController');
    Route::post('participants/update/roles', 'App\Http\Controllers\ParticipantsController@updateRoles')->name('participant.update.roles');
    Route::get('participants/selectnew/options', 'App\Http\Services\EventsService@addParticipantsOption')->name('participants.selectnew.options');
    Route::post('participants/select/event/email', 'App\Http\Services\EventsService@selectEventEmail')->name('participants.select.event.email');
    Route::post('participants/eventemail/selected', 'App\Http\Services\EventsService@eventEmailSelected')->name('participants.eventemail.selected');

    Route::resource('eventemails', 'App\Http\Controllers\EventemailsController');
    Route::post('eventemails/{eventemail}', 'App\Http\Controllers\EventemailsController@update');

    Route::resource('presentations', 'App\Http\Controllers\PresentationsController');
    Route::post('presentations/{presentation}', 'App\Http\Controllers\PresentationsController@update');
});

//auth route for both
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
    Route::get('/dashboard/profile/myprofile', 'App\Http\Controllers\DashboardController@myprofile')->name('dashboard.myprofile');

    Route::get('/profile/{user}/edit', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::post('/profile/{user}', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
    Route::get('/profile/{user}/edit-password', 'App\Http\Controllers\ProfileController@editPassword')->name('profile.edit-password');
    Route::post('/profile/{user}/update-password', 'App\Http\Controllers\ProfileController@updatePassword')->name('profile.update-password');

    Route::get('/partners/export', 'App\Http\Controllers\PartnersExportController@export');
    Route::resource('people', 'App\Http\Controllers\PeopleController')->only('index', 'show');
    Route::get('/people/sort/desc', 'App\Http\Controllers\PeopleController@indexDesc')->name('people.sort.desc');
    Route::get('/people/sort/institute', 'App\Http\Controllers\PeopleController@sortByInstitute')->name('people.sort.institute');
    Route::get('/people/sort/institute/desc', 'App\Http\Controllers\PeopleController@sortByInstituteDesc')->name('people.sort.institute.desc');
    Route::get('/people/sort/name', 'App\Http\Controllers\PeopleController@sortByLastname')->name('people.sort.name');
    Route::get('/people/sort/name/desc', 'App\Http\Controllers\PeopleController@sortByLastnameDesc')->name('people.sort.name.desc');
    Route::get('/people/sort/position', 'App\Http\Controllers\PeopleController@sortByPosition')->name('people.sort.position');
    Route::get('/people/sort/position/desc', 'App\Http\Controllers\PeopleController@sortByPositionDesc')->name('people.sort.position.desc');

    Route::resource('institutes', 'App\Http\Controllers\InstitutesController')->only('index', 'show');

    Route::resource('events', 'App\Http\Controllers\EventsController')->only('index', 'show');
    Route::get('/events/all/export', 'App\Http\Controllers\EventsExportController@export');

    Route::resource('eventemails', 'App\Http\Controllers\EventemailsController')->only('show');
    Route::resource('presentations', 'App\Http\Controllers\PresentationsController')->only('show');
});

require __DIR__.'/auth.php';

app/Models/Eventemail.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Eventemail extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'sender',
        'email_subject',
        'email_message',
        'signature',
        'event_link',
        'sent_date',
        'event_id'
    ];

    public function event()
    {
        return $this->belongsTo(Event::class);
    }
}

app/Http/Controllers/EventemailsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use App\Models\Eventemail;
use Illuminate\Http\Request;

class EventemailsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $event_id = $request->session()->get('event_id');

        $event = Event::findOrFail($event_id);
        $event_name = $event->event_name;

        return view('eventemails.create', compact('event_name'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function validateEventEmail(Request $request)
    {
        $request->validate([
            'sender' => ['required', 'string', 'email', 'max:255'],
            'email_subject' => ['required', 'string', 'max:255'],
            'email_message' => ['string', 'max:500', 'nullable'],
            'signature' => ['required', 'string', 'max:255'],
            'event_link' => ['string', 'max:255', 'active_url', 'nullable']
        ]);
    }

    public function store(Request $request)
    {
        $event_id = $request->session()->get('event_id');

        $this->validateEventEmail($request);

        $eventemail = Eventemail::create([
            'sender' => $request->sender,
            'email_subject' => $request->email_subject,
            'email_message' => $request->email_message,
            'signature' => $request->signature,
            'event_link' => $request->event_link,
            'event_id' => $event_id
        ]);

        $eventemail->save();

        return redirect()->route('eventemails.show', $eventemail->event_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $eventemails = Eventemail::where('event_id', $id)->get();
        $event = Event::findOrFail($id);

        $i = 1;

        return view('eventemails.show', compact('eventemails', 'event', 'i'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $eventemail = Eventemail::findOrFail($id);
        $event = Event::findOrFail($eventemail->event_id);
        $event_name = $event->event_name;

        return view('eventemails.edit', compact('eventemail', 'event_name'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validateEventEmail($request);

        $eventemail = Eventemail::findOrfail($id);

        $eventemail->sender = $request->get('sender');
        $eventemail->email_subject = $request->get('email_subject');
        $eventemail->email_message = $request->get('email_message');
        $eventemail->signature = $request->get('signature');
        $eventemail->event_link = $request->get('event_link');

        $eventemail->save();

        return redirect()->route('eventemails.show', $eventemail->event_id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $eventemail = Eventemail::findOrFail($id);
        $event = Event::findOrFail($eventemail->event_id);

        if($eventemail->sent_date === null){
            $eventemail->delete();
            return redirect()->route('eventemails.show', $event->id);
        } else {
            return redirect()->route('eventemails.show', $event->id)->with('status', 'Olyan esemény e-mail, ami már el lett küldve nem törölhető!');
        }
    }
}

resources/views/eventemails/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('events.sidebar-events')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új Email') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">
                        <div class="card">
                            <div class="card-header text-center">{{ $event_name }}</div>
                            <form method="POST" action="{{ route('eventemails.store') }}" enctype="multipart/form-data">
                                @csrf
                            <div class="card-body">
                                @include('components.forms.eventemail-form')
                            </div>
                                @include('components.forms.edit-footer')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/eventemails/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('events.sidebar-events')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Esemény E-mail szerkesztése') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">
                        <div class="card">
                            <div class="card-header text-center">{{ $event_name }}</div>
                            <form method="POST" action="{{ route('eventemails.update', $eventemail->id) }}" enctype="multipart/form-data">
                                @csrf
                            <div class="card-body">
                                @include('components.forms.eventemail-form')
                            </div>
                                @include('components.forms.edit-footer')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/eventemails/participants-option.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('events.sidebar-events')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új résztvevők') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header text-center">
                                <h5>{{ __('Hozzáadás módja:') }}</h5>
                            </div>

                            <div class="card-body">

                                <form method="POST" action="{{ route('participants.select.event.email') }}" enctype="multipart/form-data">
                                @csrf

                                <!--Select Option new participants -->
                                    <div class="form-group row pl-lg-5">
                                        <div class="col-md-12">
                                            <div class="form-check">
                                                <input class="form-check-input" type="radio" name="participants_option" id="option_1" value="1" checked>
                                                <label class="form-check-label" for="participants_option">{{ __('Hozzáadás meghívó küldésével') }}</label>
                                                <br>
                                                <input class="form-check-input" type="radio" name="participants_option" id="option_0" value="0">
                                                <label class="form-check-label" for="participants_option">{{ __('Hozzáadás meghívó nélkül visszaigazolt új résztvevőknek') }}</label>
                                            </div>
                                        </div>
                                    </div>

                                    @include('components.forms.partner-steps-footer', ['url' => '/events/'. $event_id])

                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/eventemails/select-email.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('events.sidebar-events')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új résztvevők') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header text-center">
                                <h5>{{ __('Email kiválasztása:') }}</h5>
                            </div>

                            <div class="card-body">

                                <form method="POST" action="{{ route('participants.eventemail.selected') }}" enctype="multipart/form-data">
                                @csrf
                                <!--Select Event Email -->
                                    <div class="form-group row">
                                        <label for="mail_id" class="col-md-4 col-form-label text-md-right">{{ __('Esemény email:') }}</label>

                                        <div class="col-md-6">
                                            @if(count($eventemails) != 0)
                                                <select name="mail_id"  class="form-select form-select-sm btn-sm">
                                                    @foreach($eventemails as $mail)
                                                        <option value="{{ $mail->id }}" >{{ $mail->email_subject }}</option>
                                                    @endforeach
                                                </select>
                                            @else
                                                <label class="col-form-label text-md-right">{{ __('Még nincsenek kiválasztható e-mailek') }}</label>
                                            @endif
                                        </div>
                                    </div>
                                    @if(count($eventemails) != 0)
                                        @include('components.forms.edit-footer')
                                    @else
                                        @include('components.forms.back-footer', ['url' => '/events/'.$event_id])
                                    @endif

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/eventemails/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('events.sidebar-events')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Esemény e-mailek') }}</h1></div>
            <div class="container user-table col-md-12">

                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th colspan="8" class="text-center">{{ $event->event_name }}</th>
                        </tr>
                        <tr>
                            <th scope="col-sm-1">{{ __('Sorszám') }}</th>
                            <th scope="col">{{ __('Küldő') }}</th>
                            <th scope="col">{{ __('Tárgy') }}</th>
                            <th scope="col">{{ __('Üzenet') }}</th>
                            <th scope="col">{{ __('Aláírás') }}</th>
                            <th scope="col">{{ __('Link') }}</th>
                            @if(Auth::user()->hasRole('admin'))
                                <th class="small-td">{{ __('Szerkeszt') }}</th>
                                <th class="small-td">{{ __('Töröl') }}</th>
                            @endif
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($eventemails as $email)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $email->sender }}</td>
                            <th scope="row">{{ $email->email_subject }}</th>
                            <td>{{ $email->email_message }}</td>
                            <td>{{ $email->signature }}</td>
                            <td>{{ $email->event_link }}</td>
                            @if(Auth::user()->hasRole('admin'))
                                @if($event->start_date > now())
                                <td>
                                    <button class="btn btn-primary">
                                        <a class="text-decoration-none text-light" href="{{ route('eventemails.edit',$email->id)}}" >
                                            @include('components.icons.edit-icon')
                                        </a>
                                    </button>
                                </td>

                                <td>
                                @if($email->sent_date === null)
                                <!-- Button trigger modal -->
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ $id = $email->id }}">
                                        @include('components.icons.delete-icon')
                                    </button>

                                    <!-- Modal -->
                                    @include('components.delede-modal', ['route' => 'eventemails.destroy', 'headertext' => 'Esemény e-mail törlése',
                                            'bodytext' => 'Biztosan törölni akarja az esemény e-mailt minden adatával?' ])

                                @endif
                                </td>
                                @endif
                            @endif
                        </tr>
                        @endforeach
                        @if(Auth::user()->hasRole('admin'))
                        <tr>
                            <td colspan="8" class="text-center">
                                <button class="btn btn-primary">
                                    <a class="text-decoration-none text-light" href="{{ route('eventemails.create') }}">{{ __('Esemény e-mail hozzáadása') }}</a>
                                </button>
                            </td>
                        </tr>
                        @endif
                    </tbody>
                </table>
                @include('components.forms.back-footer', ['url' => 'events/'.$event->id])
            </div>
            @if(session('status'))
                <div class="alert alert-danger">
                    {{ session('status') }}
                </div>
            @endif
        </div>
    </div>

@endsection