routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// for admins
Route::group(['middleware' => ['auth', 'role:admin']], function() {

    Route::get('/users/export', 'App\Http\Controllers\UsersExportController@export');
    Route::resource('users', 'App\Http\Controllers\UsersController');
    Route::post('/users/{user}', 'App\Http\Controllers\UsersController@update');

    Route::resource('people', 'App\Http\Controllers\PeopleController');
    Route::post('/people/{person}', 'App\Http\Controllers\PeopleController@update');

    Route::resource('mails', 'App\Http\Controllers\EmailsController');
    Route::post('/mails/{email}', 'App\Http\Controllers\EmailsController@update');

    Route::resource('phones', 'App\Http\Controllers\PhonesController');
    Route::post('/phones/{phone}', 'App\Http\Controllers\PhonesController@update');

    Route::resource('institutes', 'App\Http\Controllers\InstitutesController');
    Route::post('institutes/{institute}', 'App\Http\Controllers\InstitutesController@update');

    Route::get('institutes/{institute}/edit/category', 'App\Http\Controllers\InstitutesController@editCategory')->name('institutes.edit.category');
    Route::post('institutes/{institute}/update/category', 'App\Http\Controllers\InstitutesController@updateCategory')->name('institutes.update.category');

    Route::get('institutes/{institute}/edit/specialities', 'App\Http\Controllers\InstitutesController@editSpecialities')->name('institutes.edit.specialities');
    Route::post('institutes/{institute}/update/specialities', 'App\Http\Controllers\InstitutesController@updateSpecialities')->name('institutes.update.specialities');

    Route::post('institutes/for/person/{person}', 'App\Http\Controllers\InstitutesController@categoryselectedPerson')->name('institutes.for.person'); //person
    Route::post('institutes/for/person/selected/{person}', 'App\Http\Controllers\InstitutesController@selectedInstitutePerson')->name('institutes.for.person.selected'); //person
    Route::get('institutes/edit/address/{institute}', 'App\Http\Controllers\InstitutesController@editAddress')->name('institutes.edit.address');
    Route::post('institutes/{institute}/update/address', 'App\Http\Controllers\InstitutesController@updateAddress')->name('institutes.update.address');

    Route::post('institutes/category/selected', 'App\Http\Services\InstitutesService@instituteCategorySelected')->name('institutes.category.selected'); //new institute
    Route::post('institutes/select/parent', 'App\Http\Services\InstitutesService@selectParentInstitute')->name('institutes.select.parent'); //new institute
    Route::get('institutes/select/parent/back', 'App\Http\Services\InstitutesService@backSelectedParentInstitute')->name('institutes.select.parent.back'); //new institute
    Route::post('institutes/save/address', 'App\Http\Controllers\InstitutesController@saveAddress')->name('institutes.save.address'); //new institute
    Route::post('institutes/save/specialities', 'App\Http\Controllers\InstitutesController@saveSpecialities')->name('institutes.save.specialities'); //new institute

    Route::resource('categories', 'App\Http\Controllers\CategoriesController');
    Route::get('categories/index/people/{person}', 'App\Http\Controllers\CategoriesController@indexPeople')->name('categories.index.people'); //person
    Route::get('categories/edit/people/{person}', 'App\Http\Controllers\CategoriesController@editPeople')->name('categories.edit.people'); //person

    Route::resource('countries', 'App\Http\Controllers\CountriesController');
    Route::resource('cities', 'App\Http\Controllers\CitiesController');
    Route::resource('addresses', 'App\Http\Controllers\AddressesController');
    Route::resource('specialities', 'App\Http\Controllers\SpecialitiesController');

    Route::resource('events', 'App\Http\Controllers\EventsController');
    Route::post('events/{event}', 'App\Http\Controllers\EventsController@update');
    Route::get('events/send/invitation/{$id}', 'App\Http\Controllers\EventsController@sendEventMail')->name('events.send.invitation');
    Route::post('events/email/sent', 'App\Http\Controllers\EventsController@eventMailSent')->name('events.email.sent');

    Route::resource('participants', 'App\Http\Controllers\ParticipantsController');
    Route::post('participants/update/roles', 'App\Http\Controllers\ParticipantsController@updateRoles')->name('participant.update.roles');
    Route::get('participants/selectnew/options', 'App\Http\Services\EventsService@addParticipantsOption')->name('participants.selectnew.options');
    Route::post('participants/select/event/email', 'App\Http\Services\EventsService@selectEventEmail')->name('participants.select.event.email');
    Route::post('participants/eventemail/selected', 'App\Http\Services\EventsService@eventEmailSelected')->name('participants.eventemail.selected');

    Route::resource('eventemails', 'App\Http\Controllers\EventemailsController');
    Route::post('eventemails/{eventemail}', 'App\Http\Controllers\EventemailsController@update');

    Route::resource('presentations', 'App\Http\Controllers\PresentationsController');
    Route::post('presentations/{presentation}', 'App\Http\Controllers\PresentationsController@update');
});

//auth route for both
Route::group(['middleware' => ['auth']], function() {
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name('dashboard');
    Route::get('/dashboard/profile/myprofile', 'App\Http\Controllers\DashboardController@myprofile')->name('dashboard.myprofile');

    Route::get('/profile/{user}/edit', 'App\Http\Controllers\ProfileController@edit')->name('profile.edit');
    Route::post('/profile/{user}', 'App\Http\Controllers\ProfileController@update')->name('profile.update');
    Route::get('/profile/{user}/edit-password', 'App\Http\Controllers\ProfileController@editPassword')->name('profile.edit-password');
    Route::post('/profile/{user}/update-password', 'App\Http\Controllers\ProfileController@updatePassword')->name('profile.update-password');

    Route::get('/partners/export', 'App\Http\Controllers\PartnersExportController@export');
    Route::resource('people', 'App\Http\Controllers\PeopleController')->only('index', 'show');
    Route::get('/people/sort/desc', 'App\Http\Controllers\PeopleController@indexDesc')->name('people.sort.desc');
    Route::get('/people/sort/institute', 'App\Http\Controllers\PeopleController@sortByInstitute')->name('people.sort.institute');
    Route::get('/people/sort/institute/desc', 'App\Http\Controllers\PeopleController@sortByInstituteDesc')->name('people.sort.institute.desc');
    Route::get('/people/sort/name', 'App\Http\Controllers\PeopleController@sortByLastname')->name('people.sort.name');
    Route::get('/people/sort/name/desc', 'App\Http\Controllers\PeopleController@sortByLastnameDesc')->name('people.sort.name.desc');
    Route::get('/people/sort/position', 'App\Http\Controllers\PeopleController@sortByPosition')->name('people.sort.position');
    Route::get('/people/sort/position/desc', 'App\Http\Controllers\PeopleController@sortByPositionDesc')->name('people.sort.position.desc');

    Route::resource('institutes', 'App\Http\Controllers\InstitutesController')->only('index', 'show');

    Route::resource('events', 'App\Http\Controllers\EventsController')->only('index', 'show');
    Route::get('/events/all/export', 'App\Http\Controllers\EventsExportController@export');

    Route::resource('eventemails', 'App\Http\Controllers\EventemailsController')->only('show');
    Route::resource('presentations', 'App\Http\Controllers\PresentationsController')->only('show');
});

require __DIR__.'/auth.php';

app/Models/Person.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Person extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'lastname',
        'firstname',
        'title',
        'position',
        'gender',
        'manager_id',
        'description',
        'institute_id'
    ];

    public function emails()
    {
        return $this->hasMany(Email::class);
    }

    public function phones()
    {
        return $this->hasMany(Phone::class);
    }

    public function institute()
    {
        return $this->belongsTo(Institute::class);
    }

    public function events()
    {
        return $this->belongsToMany(Event::class, 'participants')->using(Participant::class);
    }

    public function presentations()
    {
        return $this->hasMany(Presentation::class);
    }
}

app/Http/Controllers/PeopleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Institute;
use App\Models\Person;
use App\Http\Services\PartnersService;
use Illuminate\Http\Request;

class PeopleController extends Controller
{
    protected $partnersService;
    protected $page;

    public function __construct(PartnersService $partnersService)
    {
        $this->partnersService = $partnersService;
        $this->page = config('constants.page');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->session()->forget(['person_id', 'category_id']);

        $people = $this->partnersService->joinInstitutesPeople($this->page);
        $institutes_specialities = Institute::with('specialities')->get();

        return view('people.index', compact('people', 'institutes_specialities'));
    }

    public function indexDesc()
    {
        $people = $this->partnersService->joinInstitutesPeopleOrdering($this->page, 'people.id', 'desc');

        $institutes_specialities = Institute::with('specialities')->get();

        return view('people.index', compact('people', 'institutes_specialities'));
    }

    public function sortByLastname()
    {
        $people = $this->partnersService->joinInstitutesPeopleOrdering2($this->page,  'people.lastname', 'people.firstname', 'asc');
        $institutes_specialities = Institute::with('specialities')->get();

        return view('people.index', compact('people', 'institutes_specialities'));
    }

    public function sortByLastnameDesc()
    {
        $people = $this->partnersService->joinInstitutesPeopleOrdering2($this->page,  'people.lastname', 'people.firstname', 'desc');
        $institutes_specialities = Institute::with('specialities')->get();

        return view('people.index', compact('people', 'institutes_specialities'));
    }

    public function sortByPosition()
    {
        $people = $this->partnersService->joinInstitutesPeopleOrdering($this->page, 'people.position', 'asc');
        $institutes_specialities = Institute::with('specialities')->get();

        return view('people.index', compact('people', 'institutes_specialities'));
    }

    public function sortByPositionDesc()
    {
        $people = $this->partnersService->joinInstitutesPeopleOrdering($this->page, 'people.position', 'desc');
        $institutes_specialities = Institute::with('specialities')->get();

        return view('people.index', compact('people', 'institutes_specialities'));
    }

    public function sortByInstitute()
    {
        $people = $this->partnersService->joinInstitutesPeopleOrdering($this->page, 'institute_path.path', 'asc');
        $institutes_specialities = Institute::with('specialities')->get();

        return view('people.index', compact('people', 'institutes_specialities'));
    }

    public function sortByInstituteDesc()
    {
        $people = $this->partnersService->joinInstitutesPeopleOrdering($this->page, 'institute_path.path', 'desc');
        $institutes_specialities = Institute::with('specialities')->get();

        return view('people.index', compact('people', 'institutes_specialities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $backUrl = $request->session()->get('backUrl');
        $person_id = $request->session()->get('person_id');

        if($backUrl === '/people/'.$person_id){
           $request->session()->forget('person_id');
        }

        if($person_id != null && $backUrl != '/people/'.$person_id){
            $person = Person::findOrfail($person_id);
            return view('people.create', compact('person'));
        } else {
            return view('people.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function validatePerson(Request $request)
    {
        $request->validate([
            'lastname' => ['required', 'string', 'max:255'],
            'firstname' => ['required', 'string', 'max:255'],
            'title' => ['string', 'max:10', 'nullable'],
            'position' => ['string', 'max:50', 'nullable'],
            'description' => ['string', 'max:500', 'nullable']
        ]);
    }

    public function store(Request $request)
    {
        $this->validatePerson($request);

        $person_id = $request->session()->get('person_id');
        $manager = $request->manager_id;

        if($person_id === null) {

            $person = Person::create([
                'lastname' => $request->lastname,
                'firstname' => $request->firstname,
                'title' => $request->title,
                'position' => $request->position,
                'description' => $request->description,
                'gender' => $request->gender
            ]);
        } else {
                $person = Person::findOrFail($person_id);
                $this->personUpdate($request, $person);
            }

        if ((int)$manager === 1) {
            $person->manager_id = $person->id;
            } else {
            $person->manager_id = null;
        }
        $person->save();
        $request->session()->put('person_id', $person->id);

        return redirect()->route('mails.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $backUrl = $request->getRequestUri();
        $request->session()->put('backUrl', $backUrl);

        $person = Person::findOrFail($id);

        $gender = ($person->gender == 'male') ? 'férfi' : 'nő';
        $manager = ($person->manager_id == $person->id) ? 'igen' : 'nem';

         if($person->institute_id != null) {
             $institute = Institute::findOrFail($person->institute_id);
             $parent_path = $this->partnersService->singlepath($institute->id);
             $specialities = $institute->specialities()->get();
            return view('people.show', compact('person', 'gender', 'manager', 'specialities', 'parent_path'));
         }
        else {
            return view('people.show', compact('person', 'gender', 'manager'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $person = Person::findOrFail($id);

        return view('people.edit', compact('person'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function personUpdate(Request $request, $person)
    {
        $this->validatePerson($request);

        $person->lastname =  $request->get('lastname');
        $person->firstname = $request->get('firstname');
        $person->title = $request->get('title');
        $person->position = $request->get('position');
        $person->description = $request->get('description');
        $person->gender = $request->get('gender');

        return $person;
    }

    public function update(Request $request, $id)
    {
        $person = Person::findOrFail($id);
        $manager = $request->manager_id;
        $this->personUpdate($request, $person);

        if($manager == 1) {
            $person->manager_id = $person->id;
        } else {
            $person->manager_id = null;
        }
        $person->save();
        return redirect()->route('people.show', $person->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $person = Person::findOrFail($id);
        $this->deletePersonIndividualInstitute($id);
        $person->delete();
        return redirect('/people');
    }

    public function deletePersonIndividualInstitute($id)
    {
        $person = Person::findOrFail($id);
        $personInstitute = Institute::findOrFail($person->institute_id);

        if((int)$personInstitute->category_id === 4)
        {
            $personInstitute->delete();
        }
    }
}

resources/views/people/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Új partner') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header">

                                <!-- Circles which indicates the steps of the form: -->
                                <div class="step-div">
                                    <span class="step step-finish"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <span class="step"></span>
                                    <button type="button" class="close" aria-label="Close">
                                        <a class="text-secondary text-decoration-none" href="{{ route('people.index') }}"><span>&times;</span></a>
                                    </button>
                                </div>
                            </div>

                            <form method="POST" action="{{ route('people.store') }}" enctype="multipart/form-data">
                                @csrf
                            <div class="card-body">

                                @include('components.forms.person-form')

                                @if(request()->session()->get('person_id') != null)
                                    @include('components.forms.person-selection-edit')
                                @else
                                    <!--Select Option manager -->
                                    <div class="form-group row">
                                        <label for="manager_id" class="col-md-4 col-form-label text-md-right">{{ __('Vezető:') }}</label>

                                        <div class="col-md-6">
                                            <select name="manager_id"  class="form-select form-select-sm btn-sm">
                                                <option value="0">{{ __('Nem') }}</option>
                                                <option value="1">{{ __('Igen') }}</option>
                                            </select>
                                        </div>
                                    </div>

                                    <!--Select Option gender type-->
                                    <div class="form-group row">
                                        <label for="gender" class="col-md-4 col-form-label text-md-right">{{ __('Neme:') }}</label>

                                        <div class="col-md-6">
                                            <select name="gender" class="form-select form-select-sm btn-sm">
                                                <option value="male">{{ __('Férfi') }}</option>
                                                <option value="female">{{ __('Nő') }}</option>
                                            </select>
                                        </div>
                                    </div>
                                @endif

                            </div>
                                @include('components.forms.partner-steps-footer', ['url' => '/people'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/people/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Partner szerkesztése') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">
                            <div class="card-header text-center">
                                <div><h5>{{ __('Alap adatok szerkesztése') }}</h5></div>
                            </div>
                            <form method="POST" action="{{ route('people.update', $person->id) }}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">

                                @include('components.forms.person-form')
                                @include('components.forms.person-selection-edit')

                            </div>
                                @include('components.forms.edit-footer')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/people/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="page">
        @include('people.sidebar-people')

        <div class="content pl-1 pr-1">
            <div Class="welcome pt-4 pb-4 d-flex justify-content-center"><h1>{{ __('Partner adatai') }}</h1></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <div class="card">

                            <div class="card-header">
                                <h3 class="text-center">{{ $person->title }} {{ $person->lastname }} {{ $person->firstname }}</h3>
                            </div>
                            <div class="card-body">
                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label text-md-right">{{ __('Beosztás:') }}</label>
                                        <label class="col-md-6 col-form-label text-md-left">{{ $person->position }}</label>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label text-md-right">{{ __('Vezető:') }}</label>
                                        <label class="col-md-6 col-form-label text-md-left">{{ $manager }}</label>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label text-md-right">{{ __('Neme:') }}</label>
                                        <label class="col-md-6 col-form-label text-md-left">{{ $gender }}</label>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label text-md-right">{{ __('Leírás:') }}</label>
                                        <label class="col-md-6 col-form-label text-md-left">{{ $person->description  }}</label>

                                        @if(Auth::user()->hasRole('admin'))
                                        <div class="col-md-3">
                                            <button class="btn btn-primary">
                                                <a class="text-light" href="{{ route('people.edit', $person->id )}}">@include('components.icons.edit-icon')</a>
                                            </button>
                                        </div>
                                        @endif
                                    </div>

                                    <hr class="border-info">

                                    <div class="form-group row justify-content-end">
                                        <label for="email" class="col-md-3 col-form-label text-md-right">{{ __('E-mail:') }}</label>
                                        <ul class="col-md-6 col-form-label text-md-left">
                                            @foreach($person->emails as $email)
                                                <li>{{ $email->email_address }}</li>
                                            @endforeach
                                        </ul>
                                        <div class="col-md-3">
                                        @if(Auth::user()->hasRole('admin'))
                                            <button class="btn btn-primary">
                                                <a class="text-light" href="{{ route('mails.edit', $person->id )}}">@include('components.icons.edit-icon')</a>
                                            </button>
                                        @endif
                                        </div>

                                    </div>

                                    <hr class="border-info">

                                    <div class="form-group row justify-content-end">
                                        <label for="phone" class="col-md-3 col-form-label text-md-right">{{ __('Telefon:') }}</label>
                                            <ul class="col-md-6 col-form-label text-md-left">
                                        @foreach($person->phones as $phone)
                                                <li>{{ $phone->phone_number }}</li>
                                        @endforeach
                                            </ul>

                                        <div class="col-md-3">
                                        @if(Auth::user()->hasRole('admin'))
                                            <button class="btn btn-primary">
                                                <a class="text-light" href="{{ route('phones.edit', $person->id )}}">@include('components.icons.edit-icon')</a>
                                            </button>
                                        @endif
                                        </div>
                                    </div>

                                <hr class="border-info">

                                @if($person->institute_id != null)
                                <div class="form-group row justify-content-end">
                                    <label class="col-md-3 col-form-label text-md-right">{{ __('Intézmény:') }}</label>
                                    <label class="col-md-5 col-form-label text-md-left">
                                        @for($i = count($parent_path)-1; $i >= 0; $i--)
                                            @if($i == 0)
                                                <strong>{{ $parent_path[$i]['institute_name'] }}</strong>
                                            @else
                                                {{ $parent_path[$i]['institute_name'] }}
                                            @endif
                                            <br>
                                        @endfor
                                    </label>

                                    <div class="col-md-4">
                                        <button class="btn  btn-success btn-show">
                                            <a class="text-light" href="{{ route('institutes.show', $person->institute_id )}}">@include('components.icons.eye-icon')</a>
                                        </button>
                                        @if(Auth::user()->hasRole('admin'))
                                            <button class="btn btn-primary ">
                                                <a class="text-decoration-none text-light" href="{{ url('categories/edit/people/'.$person->id) }}">@include('components.icons.edit-icon')</a>
                                            </button>
                                        @endif
                                    </div>

                                </div>
                                <div class="form-group row justify-content-center">
                                    @foreach($specialities as $speciality)
                                        <span class="badge badge-pill {{ $speciality->colour_class }}">
                                            {{ $speciality->speciality_name }}
                                        </span>
                                    @endforeach
                                </div>

                                @else
                                <div class="form-group row justify-content-center">
                                    @if(Auth::user()->hasRole('admin'))
                                        <button class="btn btn-primary">
                                            <a class="text-decoration-none text-light" href="{{ url('categories/edit/people/'.$person->id) }}">{{ __('Intézmény hozzáadása') }}</a>
                                        </button>
                                    @endif
                                </div>
                                @endif

                            </div>
                                @include('components.forms.back-footer', ['url' => 'people'])
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection